# Generated by Django 5.1.3 on 2025-04-02 13:20

import django.db.models.deletion
import django_mysql.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("camerasapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ThreatDetection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.CharField(max_length=255)),
                ("weapon_type", models.CharField(blank=True, max_length=50, null=True)),
                ("confidence", models.FloatField(null=True)),
                ("audio", models.CharField(blank=True, max_length=255, null=True)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
                ("emotion", models.CharField(max_length=50)),
                ("gender", models.CharField(max_length=10)),
                (
                    "status",
                    django_mysql.models.EnumField(
                        choices=[
                            ("pending", "Pending"),
                            ("verified", "Verified"),
                            ("false alarm", "False Alarm"),
                        ],
                        default="pending",
                    ),
                ),
                ("alert_triggered", models.BooleanField(default=False)),
                (
                    "camera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="threat_detections",
                        to="camerasapp.camera",
                    ),
                ),
            ],
            options={
                "db_table": "threat_detections",
            },
        ),
    ]
