# Generated by Django 5.2 on 2025-06-10 18:51

import django.db.models.deletion
import django_mysql.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("threatsapp", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="threatdetection",
            name="escalated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="threatdetection",
            name="escalated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="threatdetection",
            name="review_decision",
            field=django_mysql.models.EnumField(
                blank=True,
                choices=[
                    ("real", "Real"),
                    ("false", "False"),
                    ("uncertain", "Uncertain"),
                ],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="threatdetection",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Viewer who reviewed the alert",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_threats",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
