# Generated by Django 5.1.3 on 2025-04-02 09:58

import django_mysql.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("usersapp", "0001_update_auth_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="OwnerRequests",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(max_length=20)),
                ("business_details", models.TextField(blank=True, null=True)),
                ("address", models.TextField(null=True)),
                ("invoice", models.FileField(upload_to="invoices/")),
                (
                    "status",
                    django_mysql.models.EnumField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "owner_requests",
            },
        ),
    ]
