# Generated by Django 5.1.3 on 2025-04-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usersapp", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ownerrequests",
            name="invoice",
            field=models.CharField(max_length=150),
        ),
    ]
