# Generated by Django 5.2 on 2025-04-23 10:21

import django.db.models.deletion
import django_mysql.models
from django.conf import settings
from django.db import migrations, models, connection

def remove_fields_from_auth_user(apps, schema_editor):
    with connection.cursor() as cursor:
        try:
            cursor.execute("ALTER TABLE auth_user DROP COLUMN role;")
        except Exception:
            pass
        try:
            cursor.execute("ALTER TABLE auth_user DROP COLUMN phone_number;")
        except Exception:
            pass
        try:
            cursor.execute("ALTER TABLE auth_user DROP COLUMN address;")
        except Exception:
            pass
        try:
            cursor.execute("ALTER TABLE auth_user DROP COLUMN updated_at;")
        except Exception:
            pass

class Migration(migrations.Migration):

    dependencies = [
        ("usersapp", "0003_alter_ownerrequests_invoice"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    django_mysql.models.EnumField(
                        choices=[
                            ("admin", "Admin"),
                            ("owner", "Owner"),
                            ("viewer", "Viewer"),
                        ],
                        default="viewer",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("address", models.TextField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_details",
            },
        ),
        migrations.RunPython(remove_fields_from_auth_user),
    ]
