# Generated by Django 5.2 on 2025-04-24 16:46

import django_mysql.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camerasapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='location',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='status',
            field=django_mysql.models.EnumField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('deleted', 'Deleted')], default='active'),
        ),
    ]
